### ISSUE TITLE
Upgrade to AWS provider 5.0

### ISSUE THREAD

**Issue by rafaljanicki** [umotif-public/terraform-aws-waf-webaclv2#108]
**What is the current behavior?**
Currently, the versions are set to <5.0.0 what breaks usage with the newest AWS provider

**What is the expected behavior?**
Support AWS provider >= 5.0.0 < 6.0.0

**Comment by nileshgadgi** [comment]
**Yes, Agree**
Module should be updated for the latest version of AWS provider.

**Comment by Ohid25** [comment]
Fixed with [5.0.0](https://github.com/umotif-public/terraform-aws-waf-webaclv2/releases/tag/5.0.0)
