### ISSUE TITLE
Ability to Log web ACL traffic to cloud watch

### ISSUE THREAD

**Issue by Mostafa-DE0** [umotif-public/terraform-aws-waf-webaclv2#137]
I'm trying to enable cloud watch logging and can't see anything related to it I would appreciate any help. Thanks

**Comment by tropnikovvl** [comment]
Works great if you add CloudWatch ARN here

https://github.com/umotif-public/terraform-aws-waf-webaclv2?tab=readme-ov-file#input_log_destination_configs

**Comment by Mostafa-DE0** [comment]
Oh, that's weird, the first time I tried the same thing it didn't work, but now it's working fine. Thank you for your time
