### ISSUE TITLE
add support for block custom_response

### ISSUE THREAD

**Issue by pessoa** [umotif-public/terraform-aws-waf-webaclv2#42]
Can we get support for:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#custom_response

Is there a workaround to set custom responses currently?

**Comment by Nitzanyan** [comment]
> Can we get support for: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#custom_response
> 
> Is there a workaround to set custom responses currently?

Any update please ?

**Comment by Ohid25** [comment]
Sincere apologies for the extremely late response. 

Unfortunately, we have not been able to add this new feature as it's a really low priority and there are no plans the future to add this feature at the moment. 

Feel free to add this in and raise a PR, where we can review it.

**Comment by rsmets** [comment]
This was just addressed in https://github.com/umotif-public/terraform-aws-waf-webaclv2/pull/56

Yet to be released but looking like will be `3.8.0`
