### ISSUE TITLE
WAFv2 Multiple Conditions in the same rule

### ISSUE THREAD

**Issue by meirfine** [umotif-public/terraform-aws-waf-webaclv2#61]
Hi all,

Thanks for sharing this module. 
I have a sort of question, 
I'm migrating my old WAFv1 rules to WAFv2 Rules and some of the rules have multiple conditions as I shown bellow,

```hcl
rules = [ {
    name     = "URI_CONDITION"
    priority = 1
    action   = "block"

    and_statement = {
      statements = [ 
        {
             and_statment_condition_1
        },
        {
        or_statement = {
            statements  = [
              {
                    or_statment_condition_1
              },
              {
                    or_statment_condition_2
              }

            ]

         }
       }
      ]
    }
}]
```
another rule type but this time with not_statment & and_statment & or_statment
```hcl
rule = [ {
    name     = "URI_CONDITION"
    priority = 1
    action   = "block"

    not_statment = {
       and_statement = {
          statements = [ 
          {
             and_statment_condition_1
          },
         {
          not_statment = {
            or_statement = {
               statements  = [
                {
                    or_statment_condition_1
                },
                {
                    or_statment_condition_2
                }
              ]
            }
          }
        }
      ]
    }
}]
```
Does the module support such a structure of rules?
> AWS Supporting the above rules via awscli command (JSON structure).

Thanks

**Comment by cloudboyd** [comment]
I face same issue, see below error when apply:
<img width="1175" alt="Screen Shot 2022-05-29 at 02 49 21" src="https://user-images.githubusercontent.com/77258023/170840799-779a3837-067a-4acf-960c-3911703c9382.png">

**Comment by drey143** [comment]
@cloudboyd how were you able to fix your issue? I'm facing the same issue
