### ISSUE TITLE
Add new support for `regex_match_statement`

### ISSUE THREAD

**Issue by cloudboyd** [umotif-public/terraform-aws-waf-webaclv2#71]
See in `hashicorp/terraform-provider-aws` [v4.34.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.34.0), it starts supporting `regex_match_statement` (costs 3 wcu as base).

This could help reducing WCU usage compare to `regex_pattern_set_reference_statement` that costs 25 wcu, in case if we just want to compare 1 regular expression, if you can add this new capability will be appreciate.

**Comment by fabricef-p** [comment]
it seems `regex_match_statement` support is available as following PR: https://github.com/umotif-public/terraform-aws-waf-webaclv2/pull/63
