### ISSUE TITLE
Or statement does not seem to work

### ISSUE THREAD

**Issue by yatmengho** [umotif-public/terraform-aws-waf-webaclv2#72]
**description**

Hi,

I have created the WAF terraform that refer to the WAF module

 {
    name     = "BlockDomainRule"
    priority = "2"

    action = "block"

    visibility_config = {
        metric_name                = "BlockDomainRule-metric"
    }

    or_statement = { 
      statements = {
      byte_match_statement = {
        field_to_match = {
          single_header = "\\\"host\\\" "
        }
        positional_constraint = "CONTAINS"
        search_string         = "privacysign.org"
        priority              = 3
        type                  = "NONE"
      },
      byte_match_statement = {
        field_to_match = {
          single_header = "\\\"host\\\" "
        }
        positional_constraint = "CONTAINS"
        search_string         = "secure.trytiponlineresult.com"
        priority              = 3
        type                  = "NONE"
      },
    }
   }

**What is the current behavior?**
When i terraform plan this script, i did not see the rules populated under the plan file

 rule {
          + name     = "BlockDomainRule"
          + priority = 2

          + action {

              + block {
                }
            }

          + statement {

              + or_statement {
                  + statement {  #There should have rules populated inside this block
                    }
                }
            }

          + visibility_config {
              + cloudwatch_metrics_enabled = true
              + metric_name                = "BlockDomainRule-metric"
              + sampled_requests_enabled   = true
            }
        }

And i get this error when i terraform apply.

RespMetadata: {
     StatusCode: 400,
     RequestID: "41cbb375-5873-478b-918b-e8227e975874"
   },
   Field: "OR_STATEMENT",
   Message_: "Error reason: You haven't met a minimum requirement for a threshold setting. Examples include a rule group capacity setting that's too low and an OR statement with only one nested statement., field: OR_STATEMENT, parameter: OrStatement",
   Parameter: "OrStatement",
   Reason: "You haven't met a minimum requirement for a threshold setting. Examples include a rule group capacity setting that's too low and an OR statement with only 
one nested statement."
 }

**What is the expected behavior?**

Statement block should be populated with byte match statement

**Software versions?**

Terraform v1.3.3
on windows_amd64

**Comment by Ohid25** [comment]
If you look at the [examples folder](https://github.com/umotif-public/terraform-aws-waf-webaclv2/blob/main/examples/wafv2-and-or-rules/main.tf#L91), you should be able to notice that the `statements` block is encased in square brackets, instead of curly brackets, so based on the configuration you have posted, it should be:

```
{
    name = "BlockDomainRule"
    priority = "2"
    
    action = "block"
    
    visibility_config = {
        metric_name                = "BlockDomainRule-metric"
    }
    
    
    or_statement = { 
      statements = [
      {
        byte_match_statement = {
            field_to_match = {
              single_header = "\\\"host\\\" "
            }
            positional_constraint = "CONTAINS"
            search_string         = "privacysign.org"
            priority              = 3
            type                  = "NONE"
         }
      },
      { 
        byte_match_statement = {
            field_to_match = {
              single_header = "\\\"host\\\" "
            }
            positional_constraint = "CONTAINS"
            search_string         = "secure.trytiponlineresult.com"
            priority              = 3
            type                  = "NONE"
          },
       }
    ]
  }
}
```

(of course, please validate this with `terraform validate` just in case there's a bracket missing or something)
