### ISSUE TITLE
size_constraint_statement -> field_to_match -> body {} block seems to not work.

### ISSUE THREAD

**Issue by red73ver** [umotif-public/terraform-aws-waf-webaclv2#73]
**What is the current behavior?**
When trying to put anything in "rules -> size_constraint_statement -> field_to_match -> body {}" block, it does not have any effect on existing rule, nor newly created one.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

     size_constraint_statement = {
        field_to_match = {
          body = {
            oversize_handling = "CONTINUE"
          }

I tried also put raw JSON variable into body = {} block, for example: 

 `"Body": { "OversizeHandling": "CONTINUE" }`

but nothing is happening ( terraform does not want to update existing rules - when create new rule, it trying to create empty body{} block.

**What is the expected behavior?**
Expected behavior is to take into account rules -> size_constraint_statement -> field_to_match -> body {} block and create / update relevant rule, in this case oversize_handling.

Oversize Handling becoming required parameter to set and AWS sent to its users notification to update WAFs until 28/Feb/2023. Taking this into account I would like to be able to set/update oversize_handling by this WAF module.

**Software versions?**
TF: 1.2.6
Provider: 4.24.0
module: 3.8.1

**Comment by shiron-babi** [comment]
@red73ver  - I encountered the same issues. 
Software versions?
TF: v1.3.4
Provider: v4.47.0
module: 3.8.1

**Comment by Ohid25** [comment]
Hopefully this will be resolved with [4.52](https://github.com/hashicorp/terraform-provider-aws/pull/29082) release

**Comment by Ohid25** [comment]
Hopefully, this is now fixed with the [4.1.0](https://github.com/umotif-public/terraform-aws-waf-webaclv2/releases/tag/4.1.0) release - if not, please raise another issue, and we'll tackle it as soon as we can.
