### ISSUE TITLE
override_action for AWS Managed Rule

### ISSUE THREAD

**Issue by amit20190** [umotif-public/terraform-aws-waf-webaclv2#74]
When trying to add override rule for AWS Managed rule (e.g. AWSManagedRulesAnonymousIpList)
As seen below, how can I apply this override rule?

      name= "AWSManagedRulesAnonymousIpList"
      override_action  = "none"
      priority= 5
      visibility_config = {
        cloudwatch_metrics_enabled = true
        metric_name                = "AWSManagedRulesAnonymousIpList-metric"
        sampled_requests_enabled   = true
      }
          managed_rule_group_statement = {
            name        = "AWSManagedRulesAnonymousIpList"
            vendor_name = "AWS"
            excluded_rule = []
            **override_action = [
              {
                Name = "HostingProviderIPList",
                action_to_use ="Challenge"
              }
            ]**
          }

##########################################
Possible for someone to add update to allow "rule_action_override"?  Thanks in Advance! such as:

      statement {

        dynamic "managed_rule_group_statement" {
          for_each = length(lookup(rule.value, "managed_rule_group_statement", {})) == 0 ? [] : [lookup(rule.value, "managed_rule_group_statement", {})]
          content {
            name        = lookup(managed_rule_group_statement.value, "name")
            vendor_name = lookup(managed_rule_group_statement.value, "vendor_name", "AWS")
            version     = lookup(managed_rule_group_statement.value, "version", null)

            dynamic "excluded_rule" {
              for_each = length(lookup(managed_rule_group_statement.value, "excluded_rule", {})) == 0 ? [] : toset(lookup(managed_rule_group_statement.value, "excluded_rule"))
              content {
                name = excluded_rule.value
              }
            }

            **
            # Override the rule default action
            dynamic "rule_action_override" {
              for_each = length(lookup(managed_rule_group_statement.value, "rule_action_override", {})) == 0 ? [] : [1]
              content {
                dynamic "none" {
                  for_each = lookup(managed_rule_group_statement.value, "rule_action_override", {}) == "none" ? [1] : []
                  content {}
                }

                dynamic "count" {
                  for_each = lookup(managed_rule_group_statement.value, "rule_action_override", {}) == "count" ? [1] : []
                  content {}
                }

                dynamic "captcha" {
                  for_each = lookup(managed_rule_group_statement.value, "rule_action_override", {}) == "captcha" ? [1] : []
                  content {}
                }
                dynamic "challenge" {
                  for_each = lookup(managed_rule_group_statement.value, "rule_action_override", {}) == "challenge" ? [1] : []
                  content {}
                }
              }
            }**

            dynamic "scope_down_statement" {
              for_each = length(lookup(managed_rule_group_statement.value, "scope_down_statement", {})) == 0 ? [] : [lookup(managed_rule_group_statement.value, "scope_down_statement", {})]

**Comment by joaosenaecho** [comment]
Same! If someone can update it it will be cool.
