### ISSUE TITLE
Getting Error in AWSManagedRulesBotControlRuleSet for  aws_managed_rules_bot_control_rule_set

### ISSUE THREAD

**Issue by Ritesh-Goyal** [umotif-public/terraform-aws-waf-webaclv2#88]
I am getting below error

 Error: updating WAFv2 WebACL (7dd5cdf1-9bdd-47a0-ab12-cfaf037a381f): WAFInvalidParameterException: Error reason: EXACTLY_ONE_CONDITION_REQUIRED, field: RULE_ACTION, parameter: RuleAction │ { │   RespMetadata: { │     StatusCode: 400, │     RequestID: "4557c022-63bd-40a1-88ef-b1f684ba3a95" │   }, │   Field: "RULE_ACTION", │   Message_: "Error reason: EXACTLY_ONE_CONDITION_REQUIRED, field: RULE_ACTION, parameter: RuleAction", │   Parameter: "RuleAction", │   Reason: "You have used none or multiple values for a field that requires exactly one value." │ }

Below is the code

`{
name = "BotControl_AWSManagedRulesBotControlRuleSet"
priority = "0"

  override_action = "none"
  //action = "allow"

  visibility_config = {
    cloudwatch_metrics_enabled = false
    metric_name                = "BotControl_AWSManagedRulesBotControlRuleSet-metric"
    sampled_requests_enabled   = false
  }

  managed_rule_group_statement = {
    name        = "AWSManagedRulesBotControlRuleSet"
    vendor_name = "AWS"
    managed_rule_group_configs = [
      {
        aws_managed_rules_bot_control_rule_set = {
          inspection_level = "COMMON"
        }
      }
    ]
     rule_action_override = [
      {
        action_to_use = {
          allow = {}
        }
        name = "CategoryAdvertising"
      },
       {
        action_to_use = {
          allow = {}
        }
        name = "CategoryArchiver"
      },
      {
        action_to_use = {
          allow = {}
        }
        name = "CategoryContentFetcher"
      },
      {
        action_to_use = {
          allow = {}
        }
        name = "CategoryEmailClient"
      },
      {
        action_to_use = {
          allow = {}
        }
        name = "CategoryHttpLibrary"
      },
      {
        action_to_use = {
          allow = {}
        }
        name = "CategoryLinkChecker"
      },
      {
        action_to_use = {
          allow = {}
        }
        name = "CategoryMiscellaneous"
      },
      {
        action_to_use = {
          allow = {}
        }
        name = "CategoryMonitoring"
      },
      {
        action_to_use = {
          allow = {}
        }
        name = "CategoryScrapingFramework"
      },
      {
        action_to_use = {
          allow = {}
        }
        name = "CategorySearchEngine"
      }
    ]
  }
}`

**Comment by Ohid25** [comment]
With the release of 4.1.2, you should use `rule_action_overrides (plural)` instead of just `rule_action_override`

```
{
	name = "BotControl_AWSManagedRulesBotControlRuleSet"
	priority = "0"

	override_action = "none"
	//action = "allow"

	visibility_config = {
		cloudwatch_metrics_enabled = false
		metric_name = "BotControl_AWSManagedRulesBotControlRuleSet-metric"
		sampled_requests_enabled = false
	}

	managed_rule_group_statement = {
		name = "AWSManagedRulesBotControlRuleSet"
		vendor_name = "AWS"
		managed_rule_group_configs = [{
			aws_managed_rules_bot_control_rule_set = {
				inspection_level = "COMMON"
			}
		}]
		rule_action_overrides = [{
				action_to_use = {
					allow = {}
				}
				name = "CategoryAdvertising"
			},
                          ...
                          ...
                          ...
			{
				action_to_use = {
					allow = {}
				}
				name = "CategorySearchEngine"
			}
		]
	}
}
```
