### ISSUE TITLE
Support for cookie matching 

### ISSUE THREAD

**Issue by slimm609** [umotif-public/terraform-aws-waf-webaclv2#89]
**What is the current behavior?**
Not supported

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#cookies.  Cookies are supported by the TF module 

**What is the expected behavior?**
create a rule with cookie support

**Software versions?**
The WAF terraform provider added cookie support prior to 4.40.0 but any recent version has the support.

**Comment by Ohid25** [comment]
Thank you @felipe88alves for the PR. This feature is now available with [4.2.0](https://github.com/umotif-public/terraform-aws-waf-webaclv2/releases/tag/4.2.0) release.
