### ISSUE TITLE
Unable to use multiple rule_action_overrides. Not getting any error in terraform apply

### ISSUE THREAD

**Issue by Ritesh-Goyal** [umotif-public/terraform-aws-waf-webaclv2#90]
**What is the current behavior?**
Unable to override the rule action and not getting any error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

module "waf" {
  source  = "umotif-public/waf-webaclv2/aws"
  version = "~> 4.0.0"

  name_prefix = "test-waf-"

  scope = "REGIONAL"

  create_alb_association = false

   //allow_default_action = true # set to allow if not specified

  visibility_config = {
    metric_name = "test-waf-setup-waf-main-metrics"
  }

  rules = [
    {
      name     = "AWSManagedRulesCommonRuleSet-rule-1"
      priority = "1"

      override_action = "none"

      visibility_config = {
        metric_name = "AWSManagedRulesCommonRuleSet-metric"
      }

      managed_rule_group_statement = {
        name        = "AWSManagedRulesCommonRuleSet"
        vendor_name = "AWS"
        rule_action_overrides = [
          {
            action_to_use = {
              allow = {}
            }
            name = "NoUserAgent_HEADER"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "UserAgent_BadBots_HEADER"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "SizeRestrictions_QUERYSTRING"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "SizeRestrictions_Cookie_HEADER"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "SizeRestrictions_BODY"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "SizeRestrictions_URIPATH"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "EC2MetaDataSSRF_BODY"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "EC2MetaDataSSRF_COOKIE"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "EC2MetaDataSSRF_URIPATH"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "EC2MetaDataSSRF_QUERYARGUMENTS"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "GenericLFI_QUERYARGUMENTS"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "GenericLFI_URIPATH"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "GenericLFI_BODY"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "RestrictedExtensions_URIPATH"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "RestrictedExtensions_QUERYARGUMENTS"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "GenericRFI_QUERYARGUMENTS"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "GenericRFI_BODY"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "GenericRFI_URIPATH"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CrossSiteScripting_COOKIE"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CrossSiteScripting_QUERYARGUMENTS"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CrossSiteScripting_BODY"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CrossSiteScripting_URIPATH"
          }
        ]
      }
    },
    {
      name     = "AWSManagedRulesKnownBadInputsRuleSet-rule-2"
      priority = "2"

      override_action = "none"

      visibility_config = {
        metric_name = "AWSManagedRulesKnownBadInputsRuleSet-metric"
      }

      managed_rule_group_statement = {
        name        = "AWSManagedRulesKnownBadInputsRuleSet"
        vendor_name = "AWS"
      }
    },
    {
      name     = "AWSManagedRulesPHPRuleSet-rule-3"
      priority = "3"

      override_action = "none"

      visibility_config = {
        cloudwatch_metrics_enabled = false
        metric_name                = "AWSManagedRulesPHPRuleSet-metric"
        sampled_requests_enabled   = false
      }

      managed_rule_group_statement = {
        name        = "AWSManagedRulesPHPRuleSet"
        vendor_name = "AWS"
      }
    },
    {
      name     = "IpReputation_AWSManagedRulesAmazonIpReputationList"
      priority = "4"

      override_action = "none"

      visibility_config = {
        cloudwatch_metrics_enabled = false
        metric_name                = "IpReputation_AWSManagedRulesAmazonIpReputationList-metric"
        sampled_requests_enabled   = false
      }

      managed_rule_group_statement = {
        name        = "AWSManagedRulesPHPRuleSet"
        vendor_name = "AWS"
        rule_action_overrides = [
          {
            action_to_use = {
              allow = {}
            }

            name = "AWSManagedIPReputationList"
          },
          {
            action_to_use = {
              allow = {}
            }

            name = "AWSManagedReconnaissanceList"
          },
          {
            action_to_use = {
              allow = {}
            }

            name = "AWSManagedIPDDoSList"
          }
        ]
      }
    },
    {
      name     = "BotControl_AWSManagedRulesBotControlRuleSet"
      priority = "5"

      override_action = "none"

      visibility_config = {
        cloudwatch_metrics_enabled = false
        metric_name                = "BotControl_AWSManagedRulesBotControlRuleSet-metric"
        sampled_requests_enabled   = false
      }

      managed_rule_group_statement = {
        name        = "AWSManagedRulesBotControlRuleSet"
        vendor_name = "AWS"
        rule_action_overrides = [
          {
            action_to_use = {
              allow = {}
            }
            name = "CategoryAdvertising"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CategoryArchiver"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CategoryContentFetcher"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CategoryEmailClient"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CategoryHttpLibrary"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CategoryLinkChecker"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CategoryMiscellaneous"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CategoryMonitoring"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CategoryScrapingFramework"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CategorySearchEngine"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CategorySecurity"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CategorySeo"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "CategorySocialMedia"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "SignalAutomatedBrowser"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "SignalKnownBotDataCenter"
          },
          {
            action_to_use = {
              allow = {}
            }
            name = "SignalNonBrowserUserAgent"
          }
        ]
      }
    }
  ]

  tags = {
    "Name" = "test-waf-setup"
    "Env"  = "test"
  }
}

**What is the expected behavior?**
It should apply all "rule_action_overrides"

**Software versions?**

**Comment by felipe88alves** [comment]
From looking at the module code, it seems like there's currently only support for the `count` action.

**Comment by Ohid25** [comment]
This is now supported thanks to @tim-koehler in the [5.1.0](https://github.com/umotif-public/terraform-aws-waf-webaclv2/releases/tag/5.1.0) release.

**Comment by n2taylor** [comment]
~The `allow` support isn't quite the issue here. The issue is providing _multiple_ `rule_action_override` list items. I am seeing the same issue in 5.1.0 - adding multiple overrides leads to no change in the `terraform plan` (my use case is almost exactly the same as what was provided above in the original issue report)~
It was a separate issue in my case, ignore...
